version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: air
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=dev
    depends_on:
      - db
    volumes:
      - ./..:/app
    stop_signal: SIGTERM

  db:
    # mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=gin_hexagonal_example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
