version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: container/Dockerfile
    image: gin_hexagonal_example
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
    depends_on:
      - db

  db:
    # mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=gin_hexagonal_example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
