# https://taskfile.dev

version: '3'

tasks:
  tidy:
    cmds:
      - go mod tidy
      - go mod vendor
  gen:
    cmds:
      - go generate ./...
      - oapi-codegen -generate types,gin -o internal/application/handler/http/apigen/apigen.go -package http_apigen docs/server/doc.yaml
  dev:
    cmds:
      - docker compose -f container/docker-compose.dev.yaml up --build
  utest:
    cmds:
      - APP_ENV=test APP_PWD=$(pwd) ginkgo -r -v ./...
  utest-watch:
    cmds:
      - APP_ENV=test APP_PWD=$(pwd) ginkgo watch -r -v ./...
  utest-coverage:
    cmds:
      - APP_ENV=test APP_PWD=$(pwd) ginkgo -r --output-dir=./ --coverprofile=.coverprofile.out ./...
