# https://taskfile.dev

version: '3'

tasks:
  tidy:
    cmds:
      - go mod tidy
      - go mod vendor
  dev:
    cmds:
      - docker compose -f container/docker-compose.dev.yaml up --build
  utest:
    cmds:
      - APP_ENV=test APP_PWD=$(pwd) ginkgo watch --coverprofile=.coverage-report.out ./...
  gen:
    cmds:
      - oapi-codegen -generate types,gin -o internal/adapter/handler/http/apigen/apigen.go -package apigen docs/server/doc.yaml
