app:
  name: gin-hexagonal-example
  version: 1.0.0
  port: 8080
  env: dev

database:
  host: db
  port: 27017
  username: root
  password: password
  name: gin_hexagonal_example_dev

jwt:
  secret: cQ2ulqngX9JS96MI31leH/GnNudPVr8LOLU1KL+caHow+4XLRY4LQttwEv+yNo0GsMr+4AjtMhjg633rHwdOMg==
  expiresin: 1h