app:
  name: Go Gin Application
  version: 1.0.0
  port: 8080
  env: dev

database:
  host: localhost
  port: 27017
  username: root
  password: password
  name: gin_hexagonal_example

jwt:
  secret: vSsar3708Jvp9Szi2NWZZ02Bqp1qRCFpbcTZPdBhnWgs5WtNZKnvCXdhztmeD2cmW192CF5bDufKRpayrW/isg==
  expiresin: 1h